### ISSUE TITLE
Build fails with Rack build system

### ISSUE THREAD

**Issue by cschol** [jackokring/KRTPluginA#1]
The `Makefile` defines the `RACK_DIR` environment variable incorrectly.

Here is the patch that fixes the build issue:

```
diff --git a/Makefile b/Makefile
index 94b7cba..5d23299 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,5 @@
 # If RACK_DIR is not defined when calling the Makefile, default to two directories above
-#RACK_DIR ?= ../..
-RACK_DIR = ..
+RACK_DIR ?= ../..
 
 # FLAGS will be passed to both the C and C++ compiler
 FLAGS +=
```

**Comment by squinkylabs** [comment]
I think this is related to the issue of calling the repo "VCV". it's as if the author's repo is not in a folder that is a direct child of the plugins folder.

**Comment by jackokring** [comment]
Rack/Rack-SDK/KRTPluginA is the local build tree in my user folder. Built-in KRTPluginA folder.
Repo renamed  https://github.com/jackokring/VCVPlugins

**Comment by jackokring** [comment]
Fixed build by having an extra Plugins directory.
