### ISSUE TITLE
Binaries committed to repository

### ISSUE THREAD

**Issue by cschol** [jackokring/KRTPluginA#3]
One more issue I noticed is that the `plugin.so` is committed to the repository.

To support an efficient build process on the Rack build system, which clones the repository on build, please remove the `plugin.so` binary from the repository and its history.

See [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) for a way to remove the `plugin.so` from the **repo history**.

**IMPORTANT:** Just removing the `plugin.so` with a commit is **NOT ENOUGH**, because it will remain in the repository history and take up space when cloned. Please use a tool like BFG Cleaner to accomplish this task.

**Comment by jackokring** [comment]
Ok, deleted as on the last commit can auto find? Just git push -u --force origin master ... and so just one commit.
