### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by davephillips** [jackokring/KRTPluginA#4]
VCV Rack 1.x (dev build)
Ubuntu 18.04
GCC 7.5.0

```
$ make
g++  -std=c++11 -Wsuggest-override   -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=athlon-fx -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -c -o build/src/T.cpp.o src/T.cpp
src/T.cpp: In member function ‘virtual void T::process(const rack::engine::Module::ProcessArgs&)’:
src/T.cpp:147:28: error: invalid operands of types ‘float’ and ‘float [16]’ to binary ‘operator*’
     lenL[p] = (note - 1.f) * len / (note - low);//ratio
               ~~~~~~~~~~~~~^~~~~
../../compile.mk:68: recipe for target 'build/src/T.cpp.o' failed
make: *** [build/src/T.cpp.o] Error 1
```

Any suggestions for a fix ?

Best regards,

Dave Phillips

**Comment by caoliver** [comment]
From the README: "Any commit not tagged is not a version for compile, although it may work."

git checkout v1.2.4

That's not to say build breaking commits are a good idea.

**Comment by SteveRussell33** [comment]
That line changed in 34f106922bb3b8d8d1895b7a40c0398590d78dde - build works from latest commit.

**Comment by SteveRussell33** [comment]
That line changed in 34f106922bb3b8d8d1895b7a40c0398590d78dde - build works as of d3155d71fff58614d6df6e854b5638b0656ca2af
https://github.com/jackokring/KRTPluginA/blob/34f106922bb3b8d8d1895b7a40c0398590d78dde/src/T.cpp#L150

**Comment by jackokring** [comment]
v1.8.10 tagged release is working fine. I commit as I work on generator power, and power failure is a possibility, so I commit often and sometimes without a pre-build test.
